# Generated by Django 3.0 on 2019-12-13 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ideasport_app.League')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_wo', models.BooleanField(blank=True, default=False)),
                ('player2_wo', models.BooleanField(blank=True, default=False)),
                ('mutual_wo', models.BooleanField(blank=True, default=False)),
                ('set1_player1', models.IntegerField(blank=True, null=True)),
                ('set1_player2', models.IntegerField(blank=True, null=True)),
                ('set2_player1', models.IntegerField(blank=True, null=True)),
                ('set2_player2', models.IntegerField(blank=True, null=True)),
                ('set3_player1', models.IntegerField(blank=True, null=True)),
                ('set3_player2', models.IntegerField(blank=True, null=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_match', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_match', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ideasport_app.Round')),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ideasport_app.Season'),
        ),
    ]
