# Generated by Django 3.0 on 2021-10-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideasport_app', '0003_auto_20201126_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='covid19_canceled',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
