# Generated by Django 3.0 on 2021-10-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideasport_app', '0004_league_covid19_canceled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['order']},
        ),
    ]
